In [1]:
import numpy as np
import pandas as pd

In [2]:
bd_est = pd.read_csv(r"C:\Users\Nishma\Documents\Imarticus Learning\Blog\Budget blueprint\Budget Estimates.csv").set_index("Year")
bd_est

,Pension,Defence,Subsidy,Agriculture_and_Allied_Activities,Commerce_and_Industry,Development_of_North_East,Education,Energy,External_Affairs,Finance,...,Rural_Development,Scientific_Departments,Social_Welfare,Tax_Administration,Transfer_to_States,Transport,Union_Territories,Urban_Development,Reserve,Grand_Total
Year,,,,,,,,,,,,,,,,,,,,,
2019-2020,184147,316296,227255,120835,28608,2670,94854,42458,17372,24880,...,143409,27694,48210,137307,155447,158207,15026,42267,0,2698552
2020-2021,204393,343822,595355,145355,23515,1860,85089,33440,15000,50566,...,216342,22352,39629,147728,207001,218622,51282,46791,0,3450305
2021-2022,198962,368418,433108,147764,45833,2658,88002,48684,16000,51904,...,206948,28510,44952,195351,285394,325443,57533,73850,0,3770000
2022-2023,244780,409500,521585,136279,37540,2755,99881,70936,16973,17908,...,243317,25626,46502,177343,270936,390496,69040,74546,0,4187232
2023-2024,238049,455897,413466,140533,47350,5892,108878,54989,29122,23982,...,238984,26651,46741,193695,273985,524941,66676,69271,45100,4490486
2024-2025,275103,456722,383419,140859,56502,4006,114054,63403,25277,63512,...,190675,29831,46482,207968,541384,63670,450008,39400,0,4716487
2025-2026,276618,491732,383407,171437,65553,5915,128650,81174,20517,62924,...,266817,55679,60052,186632,548649,96777,482653,-23000,0,5065345
Grand Total,1622052,2842387,2957595,1003062,304901,25756,719408,395084,140261,295676,...,1506492,216343,332568,1246024,2282796,1778156,1192218,323125,45100,28378407

In [32]:
bd_act = pd.read_csv(r"C:\Users\Nishma\Documents\Imarticus Learning\Blog\Budget blueprint\Budget Actuals.csv").set_index("Year")
bd_act

,Pension,Defence,Subsidy,Agriculture_and_Allied_Activities,Commerce_and_Industry,Development_of_North_East,Education,Energy,External_Affairs,Finance,...,Planning_and_Statistics,Rural_Development,Scientific_Departments,Social_Welfare,Tax_Administration,Transfer_to_States,Transport,Union_Territories,Urban_Development,Grand_Total
Year,,,,,,,,,,,,,,,,,,,,,
2019-2020,183955,318665,228341,112452,27299,2658,89437,43542,17246,18535,...,5479,142384,27367,44649,169331,148907,153437,15128,42054,2686330
2020-2021,208473,340094,707707,134420,21554,1854,84219,32728,14329,37038,...,3172,214246,22100,37563,146439,211475,216795,47605,46701,3509836
2021-2022,198946,366546,446150,143317,47068,2653,80352,53696,14146,57364,...,3753,228760,27772,40595,177144,274580,332238,56490,106840,3793801
2022-2023,241599,399123,530958,125875,44363,990,98567,65717,16661,11551,...,4560,238396,24041,40470,207431,273393,390508,65907,77310,4193157
2023-2024,238328,444699,412346,145995,49809,1628,123365,52405,28915,23403,...,0,241193,24657,42065,191327,0,526765,68565,403367,4443447
Grand Total,1071301,1869127,2325502,662059,190093,9783,475940,248088,91297,147891,...,16964,1064979,125937,205342,891672,908355,1619743,253695,676272,18626571

In [4]:
bd_est.index

Index(['2019-2020', '2020-2021', '2021-2022', '2022-2023', '2023-2024',
       '2024-2025', '2025-2026', 'Grand Total'],
      dtype='object', name='Year')

In [5]:
bd_dev = pd.DataFrame({
    'Pension': [], 
    'Defence': [], 
    'Subsidy': [], 
    'Agriculture_and_Allied_Activities': [],
    'Commerce_and_Industry': [], 
    'Development_of_North_East': [], 
    'Education': [],
    'Energy': [], 
    'External_Affairs': [], 
    'Finance': [], 
    'Health': [], 
    'Home_Affairs': [],
    'Interest': [], 
    'IT_and_Telecom': [], 
    'Others': [], 
    'Planning_and_Statistics': [],
    'Rural_Development': [], 
    'Scientific_Departments': [], 
    'Social_Welfare': [],
    'Tax_Administration': [], 
    'Transfer_to_States': [], 
    'Transport': [],
    'Union_Territories': [], 
    'Urban_Development': [], 
    'Reserve': [], 
    'Grand_Total': []
})
bd_dev

Empty DataFrame
Columns: [Pension, Defence, Subsidy, Agriculture_and_Allied_Activities, Commerce_and_Industry, Development_of_North_East, Education, Energy, External_Affairs, Finance, Health, Home_Affairs, Interest, IT_and_Telecom, Others, Planning_and_Statistics, Rural_Development, Scientific_Departments, Social_Welfare, Tax_Administration, Transfer_to_States, Transport, Union_Territories, Urban_Development, Reserve, Grand_Total]
Index: []

[0 rows x 26 columns]

In [6]:
common_years = bd_act.index.intersection(bd_est.index)
common_years

Index(['2019-2020', '2020-2021', '2021-2022', '2022-2023', '2023-2024',
       'Grand Total'],
      dtype='object', name='Year')

In [7]:
bd_dev = bd_act.loc[common_years] - bd_est.loc[common_years]
bd_dev = bd_dev[bd_est.columns]
bd_dev

,Pension,Defence,Subsidy,Agriculture_and_Allied_Activities,Commerce_and_Industry,Development_of_North_East,Education,Energy,External_Affairs,Finance,...,Rural_Development,Scientific_Departments,Social_Welfare,Tax_Administration,Transfer_to_States,Transport,Union_Territories,Urban_Development,Reserve,Grand_Total
Year,,,,,,,,,,,,,,,,,,,,,
2019-2020,-192,2369,1086,-8383,-1309,-12,-5417,1084,-126,-6345,...,-1025,-327,-3561,32024,-6540,-4770,102,-213,NaN,-12222
2020-2021,4080,-3728,112352,-10935,-1961,-6,-870,-712,-671,-13528,...,-2096,-252,-2066,-1289,4474,-1827,-3677,-90,NaN,59531
2021-2022,-16,-1872,13042,-4447,1235,-5,-7650,5012,-1854,5460,...,21812,-738,-4357,-18207,-10814,6795,-1043,32990,NaN,23801
2022-2023,-3181,-10377,9373,-10404,6823,-1765,-1314,-5219,-312,-6357,...,-4921,-1585,-6032,30088,2457,12,-3133,2764,NaN,5925
2023-2024,279,-11198,-1120,5462,2459,-4264,14487,-2584,-207,-579,...,2209,-1994,-4676,-2368,-273985,1824,1889,334096,NaN,-47039
Grand Total,-550751,-973260,-632093,-341003,-114808,-15973,-243468,-146996,-48964,-147785,...,-441513,-90406,-127226,-354352,-1374441,-158413,-938523,353147,NaN,-9751836

In [8]:
bd_dev.to_excel("Budget deviation.xlsx", index=True)